# Generated by Django 5.2.8 on 2025-11-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='due_date',
            field=models.DateTimeField(db_index=True, verbose_name='Срок возврата'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('returned', 'Возвращена'), ('overdue', 'Просрочена')], db_index=True, default='active', max_length=10, verbose_name='Статус'),
        ),
    ]
