# Generated by Django 5.2.8 on 2025-11-12 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('due_date', models.DateTimeField(verbose_name='Срок возврата')),
                ('returned', models.BooleanField(default=False, verbose_name='Возвращена')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
            ],
            options={
                'verbose_name': 'Выданная книга',
                'verbose_name_plural': 'Выданные книги',
                'ordering': ['-borrow_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Доступно экземпляров'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(db_index=True, max_length=13, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(db_index=True, verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название жанра'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'author'], name='books_book_title_4906cc_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['available_copies', 'genre'], name='books_book_availab_08ee20_idx'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
